### ISSUE TITLE
Allow custom FFMPEG output or FFMPEG frame serving

### ISSUE THREAD

**Issue by User-3090** [gyroflow/gyroflow#298]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

First of all let me thank you for all your time dedication that made this project possible. It's incredible!

Currently export codecs and configuration are limited to a few choices. Different users have different needs. Please allowing advanced users to set a custom FFMPEG line in a textbox to configure export codecs exactly the way they require.

If that's not possible, please consider frame serving to a custom FFMPEG binary.

Use cases for me:

* Only rate control option currently is bitrate, which is an understandable, but IMHO a sub optimal choice. Constant Quality with custom quantization parameters make much more sense in this day and age (to me).
* Allow lossless h264 (8bit) and lossless h256 (10) 4:2:0 and 4:4:4 output using NVENC with custom keyframe interval (-g option in FFMPEG). Such files with short GOP sizes are good to work with in Resolve, provide maximum quality and still result in 2-3x space savings over image sequences.

So I'm  envisioning a textbox where I could input 
```
-c:a:0 pcm_s24le -c:v hevc_nvenc -preset lossless -pix_fmt yuv444p10
```
 and hit export.

**Comment by AdrianEddy** [comment]
The problem is that we don't use ffmpeg CLI so there's no way to just pass these options, everything is called directly using C API of ffmpeg.
`pix_fmt`, `preset` and `gop` distance could be added without too much changes (but will complicate the UI even more), but other than that, I don't think it makes sense to implement custom frame passing to ffmpeg binary - it would require to rewrite half of the rendering pipeline. 

BTW: DNX output will probably be added soon

**Comment by hdosys** [comment]
Thank you for the suggestion. That would be extremely helpful. Gyroflow is so fast on a 3090 that any CPU encoding becomes the bottleneck and reduces performance to a fraction of the possible speed.

GPU encoding, on the other hand, has so few options (bitrate) that I cannot use it to produce easily editable, high quality intermediate files for Resolve. I tried to use the OFX version, but in my opinion it is not ready yet. I will file separate issues for that.

I think the UI is one of the most straightforward and simple interfaces I have seen in a long time. Would hiding these options behind an "advanced" button avoid creating clutter?

Having controls for:

- pix_fmt
- preset
- gop distance
- selection for bitrate or constant quality rate control

would be ideal and would make my workflow several times faster.

**Comment by AdrianEddy** [comment]
I'll add to that list ability to select x264/x265 tier and level

**Comment by AdrianEddy** [comment]
Done in: fa4dbaac512936db039f5390e8d0ab3d3f0858c3
https://gyroflow.xyz/devbuild/?autodownload

**Comment by hdosys** [comment]
Thank you very much for this work. Could we control the GOP Length in frames rather than as a time interval? A consistent GOP size in frames provides consistent seek performance in Resolve and other NLEs. With the current implementation, the setting must be adjusted for the frame rate of the input files, which varies frequently in my case and may even be VBR.

Ultimately, this is what I want to output to Resolve for editing:

`-profile:v rext -pix_fmt yuv444p16le --rc:v:0 vbr -tune hq -cq 0 -qmin 0 -qmax 99 -g1`

Everything works well except `-g1`; otherwise, the output edits as smoothly as ProRes in Resolve.

**Comment by AdrianEddy** [comment]
Setting keyframe distance to 0s should set it to 1 frames
You should be able to set these parameters almost directly, just change `--rc:v:0 vbr` to `-rc vbr` and remove qmin and qmax
qmin and qmax are separate APIs and not implemented in Gyroflow

**Comment by hdosys** [comment]
Thank you. I may not have been completely clear above.

`-profile:v rext -pix_fmt yuv444p16le --rc:v:0 vbr -tune hq -cq 0 -qmin 0 -qmax 99`

appears to work correctly in Gyroflow. I am confused by the statement that `-qmin` and `-qmax` have no effect, because they clearly have an effect when used in the line above. In Gyroflow, `-qmax 12` produces a file 4 times larger than `-qmax 99` when used as shown.

`0s` appears to work for all-intra, which is what I primarily need.

Still, I believe setting the keyframe distance in frames rather than seconds is preferable for the reason outlined above. What do you think?

**Comment by AdrianEddy** [comment]
Which encoder are you using? `hevc_nvenc'? Also drop all :v from the options, it won't work with it, just have `-profile rext`

**Comment by hdosys** [comment]
Yes, `hevc_nvenc`.

Both lines produce an identical file when used inside Gyroflow; in both variants, changing `-qmax` changes the file size dramatically.

`-profile:v rext -pix_fmt yuv444p16le --rc:v:0 vbr -tune hq -cq 0 -qmin 0 -qmax 99`
`-profile: rext -pix_fmt yuv444p16le -rc vbr -tune hq -cq 0 -qmin 0 -qmax 99`

**Comment by AdrianEddy** [comment]
Interesting, then it must be handled internally by ffmpeg. There are separate fields for qmin and qmax in the API and i don't set or change them

**Comment by hdosys** [comment]
I also find that the `-pix_fmt` conversion appears to be single-threaded and CPU-bound, limiting render speed to about 1/3 of the possible speed. However, this is probably more of an ffmpeg issue. Do you have control over ffmpeg threading from within Gyroflow?

With `-pix_fmt yuv444p16le`:

![image](https://user-images.githubusercontent.com/71881005/180443693-3c1f31f4-0d23-44d4-ad8e-ca1a891997c9.png)

Without:

![image](https://user-images.githubusercontent.com/71881005/180444444-f5a3f69a-3532-46e1-849d-3b4e8f1e1bd8.png)

**Comment by User-3090** [comment]
> Interesting, then it must be handled internally by ffmpeg. There are separate fields for qmin and qmax in the API and i don't set or change them

it still complains about adding -g1, though :p

**Comment by AdrianEddy** [comment]
Keep in mind that this is not a FFmpeg command line, these are only encoder parameters.

Pixel format conversion is done on the Gyroflow side (by calling ffmpeg API) and it's single threaded. The plan is to eventually replace ffmpeg conversion with GPU conversion for common formats

**Comment by AdrianEddy** [comment]
Is there a reason to convert to 4:4:4 16-bit? You won't gain any additional quality versus using original pixel format

**Comment by hdosys** [comment]
Could you help me understand why that is?

I chose 4:4:4 because Gyroflow applies a complex transformation, and I want to provide full chroma resolution for that operation. Are you saying that, if the input format is 4:2:0, Gyroflow internally performs the transformation only at 4:2:0 chroma resolution, and that all `-pix_fmt` does is let ffmpeg upscale the chroma later in the pipeline, before encoding?

I do not need or want 16 bit HEVC. `-pix_fmt yuv444p16le` is simply the only way I have found to get 4:4:4 10bit HEVC from nvenc_hevc. `yuv444p16le` is truncated to 10bit.

I am aware of `p016le`, which is said to produce 4:4:4 10bit HEVC from nvenc_hevc, but it does not work for me. It produces 4:2:0 files similar to `p010le` in my tests. I found this information [here](https://superuser.com/a/1623636).

**Comment by AdrianEddy** [comment]
> I was opting for 4:4:4 as Gyroflow applies a complex transformation and I want to give it full chroma resolution to do so. Are you saying that if input format is 4:2:0 Gyroflow will internally do the transformation only at 4:2:0 chroma resolution and all that -pix_fmt does is later in the chain let ffmpeg upscale chroma before encoding?

Yes, Gyroflow works on separate YUV planes, and it's not doing any rescaling of chroma for processing. If the input file is 4k 4:2:0 10-bit, it will process the Y plane at 3840x2160 resolution, and then it will process U and V planes at 1920x1080 resolution (this is how the pixels are stored). And if you set `pix_fmt`, the conversion is done later, after processing by Gyroflow. It is possible to make the processing after the conversion, but it's pointless and adds unnecessary scaling up of U and V planes.

**Comment by hdosys** [comment]
Is it actually pointless? When applying a fisheye correction, more source pixels are compressed into less space in the center. If this processing is performed at the source resolution, detail in the middle is lost because those pixels must be averaged to fit into less space. If the processing or canvas space were larger, information would not be lost.

What is incorrect about my reasoning?

**Comment by AdrianEddy** [comment]
But these pixels are not added magically, they are interpolated from source pixels. When you do the upscaling from 4:2:0 to 4:4:4 you still need to use an interpolation of the source pixels. Then you do the second interpolation in stabilization processing to correct fisheye and move pixels around. Both are currently Lanczos4 interpolation. In your case, the interpolation is done twice. Without pixel format conversion it's done only once.

**Comment by hdosys** [comment]
I now understand the current pipeline better. My earlier assumption about `pix_fmt` was incorrect.

For workflows in which Gyroflow output is subsequently processed in an NLE, Resolve and Vegas may perform another chroma interpolation. If Gyroflow could produce 4:4:4 using Lanczos during the same transformation step, that could avoid a lower-quality second interpolation.

Would this be technically feasible and desirable?

**Comment by AdrianEddy** [comment]
This is possible to implement in theory, but in reality it's a real pain in the ass and horrible to maintain. Sure we can do single  YUV 10-bit 4:2:0 to 4:4:4, but do you know how many pixel formats are out there? For the most basic ones, we would have to support at least 15-20, and all of them will have different math to process that. Implementing that without repeating all code for all pixel formats is really challenging and not something I would like to spend my time on. In the end, the quality gain from something like this will be minimal, if at all noticeable.
