### ISSUE TITLE
iOS build

### ISSUE THREAD

**Issue by AdrianEddy** [gyroflow/gyroflow#34]
- [X] Figure out building steps
- [x] Implement `stopAccessingSecurityScopedResource` where applicable
- [x] Selecting a file from iCloud folder doesn't work [[QTBUG-112962](https://bugreports.qt.io/browse/QTBUG-112962)]
- [x] Save security-scoped bookmark in the .gyroflow project file, to be able to open it later with the same video file
- [x] Add ability to close the calibrator
- [x] Setup CI
- [x] Exiting full screen doesn't work
- [x] Show context menu on long press
- [x] Rendering second trim from the same file doesn't work
- [x] Context menu position
- [x] Opening a project file when the output folder was never selected - render fails instead of asking for output folder
- [x] Notch
- [x] Test opening from card reader
- [x] Fix the "Cancel | Hide" buttons with large gyro chart
- [x] Scrubbing timeline causes context menu to pop up
- [ ] "Open camera_presets" directory, for using default.gyroflow
- [ ] Submit to App Store
- [ ] Consider adding CloudKit and Gyroflow-specific folder

**Comment by latenitefilms** [comment]
One thing to keep in mind is that GPL3.0 isn't allowed on the App Store.

https://www.fsf.org/blogs/licensing/more-about-the-app-store-gpl-enforcement

**Comment by latenitefilms** [comment]
@AdrianEddy - I also noticed that `gyroflow_core` doesn't work properly with the "Hardened Runtime" enabled on macOS - so I assume some fixes will be required to make this work with sandboxing on both macOS and iOS.

**Comment by latenitefilms** [comment]
Actually, I think it's just a sandboxing issue, not related to Hardened Runtime specifically.

**Comment by AdrianEddy** [comment]
what do you mean exactly by "doesn't work properly"?

**Comment by latenitefilms** [comment]
It was rendering properly with lens correction, but no stabilisation - but that's simply because it didn't have sandboxed access to the video file.

What would be amazing is if you could create a document-scope, security-scoped bookmark (where the document is the Gyroflow project) for the media when importing into Gyroflow - then you could read that bookmark data when rendering to get past sandbox restrictions. Obviously not needed for Gyroflow, as it's not sandboxed, but vital for any third party apps that are sandboxed.

**Comment by AdrianEddy** [comment]
It looks like it's not possible to render the video in the background on iOS? Do you know of any iOS app that renders the video while not being in the foreground? I tried a few and they all required the screen to be on and app in the foreground

**Comment by latenitefilms** [comment]
Nope, even Final Cut Pro (for iPad) can't.

**Comment by ellsiprod** [comment]
ciao non vedo l'ora che qualcuno riesca a fare un app per ipad pro .

**Comment by AdrianEddy** [comment]
@ellsiprod it's already available if you provide UDID ( https://udid.tech )

**Comment by ellsiprod** [comment]
Great i want test thanks

**Comment by mrhuerta** [comment]
Hi! I’d love to try! But I can’t get UDID to work on the iPad Pro, I can’t get the “get UDID” button, even if I request mobile site

**Comment by AdrianEddy** [comment]
test flight link: https://testflight.apple.com/join/e0RI1n5i

**Comment by mrhuerta** [comment]
It worked! Thanks

**Comment by ellsiprod** [comment]
Thanks!🙏
Inviato da Gmail Mobile


Il giorno mer 30 ago 2023 alle 16:42 mrhuerta ***@***.***> ha
scritto:

**Comment by Amzd** [comment]
> It looks like it's not possible to render the video in the background on iOS?

On iOS 13+ you can use `BGProcessingTaskRequest` but it gets only a few minutes of runtime per call and there is no knowing when it will be called, sometimes every few hours, sometimes 5x in a row.

I'm also pretty sure you can start a process in applicationDidEnterBackground that won't be killed for ~5 minutes. You could maybe keep video processing going for 5 mins from there then send notification that app needs to be opened again to continue.

On iOS 16+ you can **maybe** use Live Activity. I haven't personally used this but I assume it will up the probability of the `BGProcessingTaskRequest` getting started (since it might update the live activity?) not sure though.

Outside of App Store you can use either the VOIP or Now Playing trick where you just loop some silent mp3 to have a permanent background process. See this as example: https://github.com/Enovale/iOS-Discord-Bot/blob/master/SwordBot/BackgroundTask.swift

**Comment by ellsiprod** [comment]
Thanks for the tip!


Il giorno mar 19 set 2023 alle 11:11 Casper Zandbergen <
***@***.***> ha scritto:

**Comment by AdrianEddy** [comment]
> > It looks like it's not possible to render the video in the background on iOS?
> 
> On iOS 13+ you can use `BGProcessingTaskRequest` but it gets only a few minutes of runtime per call and there is no knowing when it will be called, sometimes every few hours, sometimes 5x in a row.
> 
> I'm also pretty sure you can start a process in applicationDidEnterBackground that won't be killed for ~5 minutes. You could maybe keep video processing going for 5 mins from there then send notification that app needs to be opened again to continue.
> 
> On iOS 16+ you can **maybe** use Live Activity. I haven't personally used this but I assume it will increase the probability of the `BGProcessingTaskRequest` getting started (since it might update the live activity?) not sure though.
> 
> Outside of App Store you can use either the VOIP or Now Playing trick where you just loop some silent mp3 to have a permanent background process. See this as example: https://github.com/Enovale/iOS-Discord-Bot/blob/master/SwordBot/BackgroundTask.swift

thanks for the info, but as far as I remember, all these tricks don't work with VideoToolbox. The encoder simply fails when it's not in foreground

**Comment by tonyvillage** [comment]
I've only heard today about the existence of this porting project on iOS. That's a great news! Just tested to stabilize a file from my DJI Avata (about 500mb) on iPad Air 4th gen (running latest iPadOS 17.0.2) and it crashed after few seconds after the start of the job. Do you think it is something related to the device performances or the iPad build need to be "optimized"? I also have an iPhone 13Pro, it have a newer chip compared to the one on my iPad, I'll give a try later today. I'm trying to figure it out how I can export logs file from my device in order to check the crash reason. Anyway, keep going this great job!

**Comment by AdrianEddy** [comment]
@tonyvillage I just updated the app in TestFlight, please try again and send the crash report if it happens (from within iOS)

**Comment by tonyvillage** [comment]
Updated to latest 1.5.2 (1.5.2 1518), unfortunately same crash at about 3% processing a 200mb file. I enabled the option to share analytics with developers, I hope it is enough in order to let you analyze the crash report.

**Comment by AdrianEddy** [comment]
@tonyvillage try 1.5.2.1523 now

**Comment by tonyvillage** [comment]
@AdrianEddy sorry. Still the same

**Comment by AdrianEddy** [comment]
@tonyvillage the problem is "out of memory", so I'm trying to optimize what I can
1. Can you try exporting lower resolution? like 720p even just for test
2. Can you try closing all other apps in the background before rendering?
3. What's the resolution, fps and duration of your video file? Can you maybe upload that file?
4. What's the phone model?

**Comment by AdrianEddy** [comment]
@tonyvillage try v1.5.2.1534

**Comment by tonyvillage** [comment]
Hello @AdrianEddy,
I've just tried with v1.5.2.1552

1. Exporting in 720p and 1080p works correctly. 4K still crash. 
2. All apps closed while Gyroflow is running.
3. The file I'm trying to process is 4K, 60fps, 18 seconds. You can download the video [clicking here]([https://we.tl/t-FDiEYb1aep](https://we.tl/t-FDiEYb1aep?utm_campaign=TRN_TDL_05&utm_source=sendgrid&utm_medium=email&trk=TRN_TDL_05)).
4. I'm running Gyroflow on iPad Air 4th gen, which has an A14 chip (same as iPhone 12 Pro)

**Comment by AdrianEddy** [comment]
@tonyvillage it was because it defaulted to H264, which doesn't support 10-bit on GPU, and your file is 10-bit so it used the CPU encoder, which is too much for that little processor. Latest build selected HEVC by default for 10-bit and enables GPU encoding so it should be good

**Comment by tonyvillage** [comment]
@AdrianEddy 1.5.3 works seamlessly! Great job 👏

**Comment by AdrianEddy** [comment]
Gyroflow for iOS is now available in the App Store https://apps.apple.com/us/app/gyroflow/id6447994244

**Comment by tonyvillage** [comment]
@AdrianEddy that's the best news of the day! thank you sir

**Comment by ellsiprod** [comment]
TOP!
Inviato da Gmail Mobile


Il giorno gio 12 ott 2023 alle 10:46 Sebastiano ***@***.***>
ha scritto:
