### ISSUE TITLE
Betaflight Blackbox support for damaged log files

### ISSUE THREAD

**Issue by 350d** [gyroflow/gyroflow#373]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

I have external Openloger connected on UART and `blackbox_mode = ALWAYS`, so, flight controller start to record log right after power/usb connected to it. The only way to stop it - disconnect power. In most cases log file will be finished without correct closing "tag". So, its readable, but not available to view in latest Betaflight log viewer and Gyroflow can't recognize it too.
Gyro data is there. Lets make it usable in Gyroflow!

[LOG00010.TXT](https://github.com/gyroflow/gyroflow/files/8860414/LOG00010.TXT)

**Comment by AdrianEddy** [comment]
This file is missing important header info which describes the fields and it's not possible to restore it. If you have a working file from the exact same FC and setup, then it might be possible to make it usable, but this is unlikely to become a feature in Gyroflow, as it will be different for every case and not something that can be done by an algorithm.

If you have a working file, you can copy the headers and add `E\xFFEnd of log\0` at the end of the file, and then Gyroflow might load it. Latest dev version was made more resilient to corrupted blackbox files, but it still needs these headers, which are missing in your file.

Do your changes in a hex editor though, in order to maintain all byte values and not damage the file further
