### ISSUE TITLE
5k raw video export cropped to 4k?

### ISSUE THREAD

**Issue by biejay** [gyroflow/gyroflow#408]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

Not really a Feature Request because I don't know if its somehow already possible but:

I record Videos on the GoPro in 5k so that I get the extra pixels which get cropped during stabilization and then I still get my 4k resolution. 
Can I just export it in 5k same as the raw file and edit it to 4k in post. Or should I already export it in 4k in Gyroflow?
I don't know how Gyroflow handles the Cropping? How can I get the best results?

**Comment by AdrianEddy** [comment]
If you want to crop to 4k anyway, it's better to set output resolution in Gyroflow to 4k instead of 5k. Gyroflow will crop dynamically depending on the movement of the camera, and setting it to 4k will allow it to use the extra pixels for that crop. If you set the output to 5k, it will have to interpolate these pixels to maintain your resolution.
