### ISSUE TITLE
OpenFX plugin

### ISSUE THREAD

**Issue by AdrianEddy** [gyroflow/gyroflow#42]
As a first version it can just load the .gyroflow file, with a button to open a separate Gyroflow app with that file so user can adjust all settings he wants in the UI and then pass the processing to the video editor. Later we can add fancier native UIs for the plugin

https://github.com/itadinanta/ofx-rs

**Comment by ilya-epifanov** [comment]
Hi @AdrianEddy. There's https://github.com/ilya-epifanov/gyroflow-ofx already. There are some shortcomings though that I'd like to address there.

**Comment by AdrianEddy** [comment]
Hey, I know and I was just about to contact you :) Since this new core is a separate library written in Rust (no external dependencies). I was wondering if you could update your plugin using the new core and loading .gyroflow file

**Comment by ilya-epifanov** [comment]
Doneski.
It lives in the same repo for now despite their licenses being not exactly compatible. I'll probably just remove the old one soon.
Also, I ended up pulling this repo in as a submodule. I can't depend on `gyroflow-core` with cargo now due to this repo not having a standard layout. Anyway, it works now :confetti_ball:
