### ISSUE TITLE
Improve save handling of a .gyroflow file after edit

### ISSUE THREAD

**Issue by User-3090** [gyroflow/gyroflow#501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

lastet dev of today

### What operating system are you using?

Win10

### What GPU are you using?

3090

### What happened?

When dragging a gyroflow file into gyroflow there is no option to save changes to this file. Instead one can only re export with default name, which is different from the actual gyroflow opened. Behavior is different when dragging a gyroflow file into the render queue. Then there is a way to edit and save the actual Gyroflow file. Please make the two options equal.

**Comment by AdrianEddy** [comment]
Note that "Save" button when editing render queue item only saves in the render queue, in memory. It doesn't modify the original .gyroflow file you loaded

**Comment by hdosys** [comment]
I figured this out shortly after posting, but I am unclear about the rationale. Could the workflow allow us to save an opened `.gyroflow` file under its original name? I often have many trim ranges per clip and therefore many `.gyroflow` files per clip. Editing them later is cumbersome because `export -> overwrite` does not overwrite the opened file; it overwrites the file with the clip basename.

**Comment by hdosys** [comment]
I would like the Save button to always update the opened `.gyroflow` file, whether or not it was opened from the render queue.

**Comment by hdosys** [comment]
I now have to process 3000-4000 clips with Gyroflow, and workflow issues become particularly apparent at this scale. I will file separate reports about the OFX, which I would like to use; however, because of Resolve's processing order, I have not found a workable approach for this volume.

**Comment by AdrianEddy** [comment]
depending on what you want to do, you may be able to use CLI. If you want to modify certain setting in all .gyroflow files, you may be able do that using CLI's option `export_project`, `preset` and .gyroflow file as input

**Comment by User-3090** [comment]
Thanks, I'll look into these. Still do you think having a Save button that actually saves the opened gyroflow file would be sensible to have?

**Comment by AdrianEddy** [comment]
Sure, simply nobody asked for it before and I can't predict all possible features by myself

**Comment by hdosys** [comment]
Thank you. I did not mean to sound pushy; I am simply excited to start a larger, non-drone project with Gyroflow at its core.

As an end user, I would like a Save option to be available as soon as I open a `.gyroflow` file, whether from the render queue or elsewhere. This option should update the opened file with my changes. Updating the file on disk, rather than keeping changes only in memory, would also make working with the OFX easier and more consistent.

**Comment by AdrianEddy** [comment]
It's done in 0cd1919790c9bffc3c669181c31acee95984959c 
- When loading project file now you have an option to `Save project file`
- When editing render queue item and it's a project file, on `Save` it will update the project file
- `Ctrl+S` will save the current project file, or create one (like `Export project file`)

**Comment by User-3090** [comment]
So cool, thanks!
