### ISSUE TITLE
Render queue statistics go wrong when starting export multiple times

### ISSUE THREAD

**Issue by User-3090** [gyroflow/gyroflow#505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

gh859

### What operating system are you using?

Win10

### What GPU are you using?

3090

### What happened?

![image](https://user-images.githubusercontent.com/71881005/201531419-bd748fce-5303-4be3-a3d4-ee779d154be8.png)

**Comment by AdrianEddy** [comment]
The top stats are actually more accurate, the problem was that individual files times were average since the beginning, which adapts very slowly to changing conditions (like starting to render second file). I now updated the remaining time algorithm to take last 10s into consideration instead of average since start. Top stats remain unchanged (average since start), because that one is mostly fine, and I don't want to complicate it even further
