### ISSUE TITLE
Use gravity vectors displayed as enabled, but is disabled when loding new file

### ISSUE THREAD

**Issue by User-3090** [gyroflow/gyroflow#512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

876

### What operating system are you using?

Win10

### What GPU are you using?

3090

### What happened?

When horizon lock and use gravity vectors is enabled and a new file is dragged into Gyroflow the UI suggests that use gravity vectors is still enabled while in fact it is not. Please provide a way to make horizon lock and use gravity vectors a default via default.gyroflow.

**Comment by hdosys** [comment]
The same issue occurs with the "Zooming center offset" sliders. They remain in the positions set for the previous file, but after a new file is opened, their values are neither reset nor applied. The sliders must be adjusted again for their values to take effect.

I believe these sliders should reset when a new file is loaded, then read and apply the defaults from `default.gyroflow`.

**Comment by hdosys** [comment]
I think I am encountering the following behavior in this and the other issues:

1. Clear `default.gyroflow`.
2. Open any video.
3. Adjust horizon lock, gravity vectors, and center offset.
4. Drag another video into Gyroflow.
5. The sliders and options retain their GUI state, but their backend values are cleared.
6. Create `default.gyroflow`.
7. Options that appear to be enabled are not actually enabled because the GUI does not match the backend state when creating `default.gyroflow`.

**Comment by AdrianEddy** [comment]
That was useful, fixed in 2b358e48a0d750f930809f1d0984b2827bcfb7fc

**Comment by User-3090** [comment]
Light speed dev, thank you so much for these incredibly fast fixes!
