### ISSUE TITLE
How does synchronization work for the command line?

### ISSUE THREAD

**Issue by aikinai** [gyroflow/gyroflow#629]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

First of all thanks for the amazing product; this software is so good! I'm using it for handheld Sony camera, not drone video, but it works great.

I'm trying to set up an automated pipeline that's just fire-and-forget for various handheld clips so I want to use the CLI to auto-sync and render, but I feel like the documentation on the CLI isn't very clear about syncing. I saw your other (fixed) issue about auto-sync not working sometimes, so I guess maybe it's supposed to always auto-sync? Is there any way to specify the auto-sync parameters? Or automatically skip poor sync points? When I tried the CLI

I wasn't sure if this is the right category, but I guess this is a request for more information on how the CLI handles synchronization, and ideally clearer documentation so everyone can know.

Thank you!

**Comment by AdrianEddy** [comment]
When working with CLI, your main source of settings should be a [preset](https://docs.gyroflow.xyz/app/advanced-usage/settings-presets) - you can set every setting you want there, include lens profile and set "Do autosync", and then when the preset is applied, Gyroflow will do autosync. 

Lens profiles can also contain "Do autosync" and some of the profiles in the database already do, but most of them don't, so depending on which camera and lens you use, you might already have autosync in the CLI when using that lens profile. Otherwise, Gyroflow doesn't do autosync by default.

The best way to do is to enable "Do autosync" in the preset and use that preset.
