### ISSUE TITLE
The reverse pass of smoothing algorithm

### ISSUE THREAD

**Issue by ysyscool** [gyroflow/gyroflow#717]
What is it? Is there any reference for this algorithm?

**Comment by AdrianEddy** [comment]
What do you mean? it's here https://github.com/gyroflow/gyroflow/blob/master/src/core/smoothing/plain.rs#L125-L136

**Comment by ysyscool** [comment]
> What do you mean? it's here https://github.com/gyroflow/gyroflow/blob/master/src/core/smoothing/plain.rs#L125-L136
 Yes. I want to know why we need this reverse pass?

**Comment by AdrianEddy** [comment]
Without it, the smoothing will be skewed towards the front, because we would only multiply current with next sample.
Doing reverse pass after that makes the smoothing symmetrical because we then multiply current with previous as well

This is a standard technique in signal filtering https://www.dsprelated.com/freebooks/filters/Forward_Backward_Filtering.html

**Comment by ClarkWang1214** [comment]
> Without it, the smoothing will be skewed towards the front, because we would only multiply current with next sample. Doing reverse pass after that makes the smoothing symmetrical because we then multiply current with previous as well
> 
> This is a standard technique in signal filtering https://www.dsprelated.com/freebooks/filters/Forward_Backward_Filtering.html

Hi, I want to know why Gyroflow just smooth the rotational motion without smoothing the translational motion? Thx
