### ISSUE TITLE
Side-by-side viewer

### ISSUE THREAD

**Issue by adamzimnyy** [gyroflow/gyroflow#853]
### Is there an existing feature request for this?

- [X] I have searched the existing requests

### Description

I would love to have a side-by-side viewer of unstabilised/stabilised footage 

![image](https://github.com/gyroflow/gyroflow/assets/14812161/1028ef05-9ff4-46a5-8096-3e7706862fdd)

**Comment by AdrianEddy** [comment]
Done in 1479a19. Available in latest dev build https://gyroflow.xyz/devbuild/

`Ctrl+click` on the Stabilization overview or use the `v` keyboard shortcut. Split view is possible only when stabilization overview is enabled. The stabilized video view is lower quality, because it's a cutout from the texture with stabilization overview to make this work efficiently and to make the implementation easier. Rendering both windows separately (for full quality) is too much work to be worth it

**Comment by latenitefilms** [comment]
Might be a good addition to the plugins too?

**Comment by AdrianEddy** [comment]
Very hard to do in plugins, would require a very significant rewrite of the rendering pipeline which is not something I want to touch
