### ISSUE TITLE
Lens doesn't support OSS metadata

### ISSUE THREAD

**Issue by simonwjcai** [gyroflow/gyroflow#925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Do you have latest GPU drivers installed?

- [X] I have the latest GPU drivers installed, I'm absolutely sure.

### Have you checked the documentation?

- [X] I have read the FAQ and Troubleshooting and didn't find my issue there.

### Gyroflow version

1.6.0

### What operating system are you using?

MacOS 15.1

### What GPU are you using?

M1

### What happened?

I'm using FX6 with Sony 24-105/F4 zoom lens, with OSS on. However, I've got the following error message, cannot be processed. I've checked the latest update of 1.6.0, saids it can support Zoom len with OSS. Do you have any idea?

Message: "This video cannot be stabilized, because this lens doesn't support OSS metadata. Disable lens stabilization (Optical SteadyShot) in order to use Gyroflow."

<img width="293" alt="image" src="https://github.com/user-attachments/assets/129316c9-1546-4787-8d01-f7212bcf3500">

**Comment by AdrianEddy** [comment]
It's not supported by the lens, we can't do anything about it

**Comment by dizzybro** [comment]
I noticed that I get this error when the standard stabilization is selected on camera. If I switch to active, I do not get the error. Not sure if this is a limitation of tha hardware or not...

**Comment by rgaufman** [comment]
I'm on a Tamron 50-300mm F/4.5-6.3 Di III VC VXD using a Sony ZV-E1 and Sony A7C cameras. I'm also getting this message, but other lenses without OSS work beautifully, even with camera IBIS. There's no way to my knowledge to turn off OSS without also turning off IBIS which adds a lot of motion blur.

Is this something that can be added in the future like Sony IBIS was, or is it simply impossible to add support for? - any known workarounds? Does enabling "active" work properly, or does it introduce its own shake? -- I'm currently using warp stabiliser in Final Cut which has mixed results.

Here is an example clip: https://drive.google.com/file/d/1lrEFin5JQ2hjRAxkNW6qarthE6ywaBhK/view?usp=sharing

**Comment by AdrianEddy** [comment]
It's not possible to add it because there's no OSS metadata in this case

I **think** (but I haven't verified that) that the "Active" mode in this case is IBIS + EIS. While it's not possible to disable OSS directly, I think Active mode does that behind the scenes, so that may be a good mode to record in

**Comment by rgaufman** [comment]
Thank you I’ll try that, that’s a damn shame though as the OSS makes quite a big difference to reduce motion blur when zoomed i! - it’s one of the main reasons I bought it over the non OSS version. Is this something I can complain to Tamron about? Or is this a Sony limitation?

 I’ll see if IBIS+EIS+Gyroflow works better than IBIS+OSS+WarpStabe.

**Comment by AdrianEddy** [comment]
I believe this is up to Tamron, but not sure if Sony needs to be involved too - it's possible

Tamron needs to provide the metadata from the lens, but Sony needs to recognize and record it. You can complain to both of them, but don't refer to gyroflow, refer to Catalyst Browse support

**Comment by rgaufman** [comment]
I tried testing with active and the motion data is there but both Catalyst Browse and Gyroflow don't make it particularly stable, though Catalyst does a better job:

- Original clip: https://drive.google.com/file/d/1lsBJ4e9DGCMaPI9VD4n1fayGdTVs8ccC/view?usp=sharing
- After Catalyst Browse:  https://drive.google.com/file/d/1lsXSiFhXXawUbq6Q3mxo2wZcr08nkbet/view?usp=sharing
- Warp Stabe in Final Cut: https://drive.google.com/file/d/1lsepHa5KkYN87nl9mLrbSXpWnULQGjZK/view?usp=sharing

I guess the moral of the story is don't buy a non-Sony lens with OSS for video use!

With that said, because there is less distortion than with wide lenses, and the ZV-E1 has a fairly fast read out, warp stabe in Final Cut seems to do a reasonable job for the most part. Bit disappointing though.

I'll try reaching out to Tamron.

**Comment by movinimage** [comment]
I get this same message, but Gyroflow has the motion data and stabilizes the footage. So, I am confused.

I am using the Sony FX30 with the 10-18 f4 OSS lens.  I am using IBIS.

<img width="1726" height="1076" alt="Image" src="https://github.com/user-attachments/assets/27b751a3-59d0-4b9c-abab-8dce5c6e282a" />

<img width="1728" height="1084" alt="Image" src="https://github.com/user-attachments/assets/da19aae5-ddeb-43d2-984a-336601fbea74" />

**Comment by AdrianEddy** [comment]
gyro data is not affected  by this, but when you see this message - the lens OSS data is not present so if the lens element moves too much - it messes up the stabilization. Disable OSS in the lens to avoid this issue. This is a lens firmware limitation

**Comment by movinimage** [comment]
I understand. Thank you. I am using an FX30, and there is no menu option to just turn off OSS. You can turn off IBIS which from my research I *think* also turns off OSS. GF can work with IBIS on though, correct?  Basically Sony won't let me separate the two which is a stupid limitation.

Do I understand this correctly?

If so - do you happen to know if there is an OSS contact on the lens that can be blocked? :) Could that work?

**Comment by AdrianEddy** [comment]
Yes your understanding is correct. I'm not aware of any pins. On some lenses there's a physical switch to disable OSS, but on lenses without the switch you have to disable IBIS as well. You could also try the "Active" mode - I believe this is IBIS + EIS in this case, and that mode should be supported in gyroflow

**Comment by movinimage** [comment]
Thanks. I really don't want active because of the crop, and the pre-applied digital efx. 

I get that Sony wants to integrate OSS/IBIS into a single stabilization tech with them working together - but only a very limited selection of their OSS lenses actually support this. So basically if I want IBIS with Gyro in post...I need to sell my 10-18 OSS and buy the newer 10-20 that doesn't doesn't have OSS, then I can turn on IBIS and use Gyro.  Stupid.

**Comment by AdrianEddy** [comment]
I know it sucks, but on the other hand no other company/camera has the ability to use IBIS or OSS, so the fact that Sony allows that is already amazing. Older lenses are probably just not capable of sending this data

**Comment by movinimage** [comment]
Good point. I’m picking up a used 10-20. I’ll report back!
